export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const SHOW_LOADER = 'SHOW_LOADER'